global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'python-app'
    metrics_path: /
    static_configs:
      - targets: ['host.docker.internal:8001']
  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
